"""previsao do tempo: forecast_run, forecast_daily

Revision ID: 430aaeab1b2e
Revises: aa70cbea6765
Create Date: 2026-10-02 16:20:59.777131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430aaeab1b2e'
down_revision = 'aa70cbea6765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('municipality_ibge', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['municipality_ibge'], ['municipality.ibge_code'], name=op.f('fk_forecast_run_municipality_ibge_municipality')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_run'))
    )
    with op.batch_alter_table('forecast_run', schema=None) as batch_op:
        batch_op.create_index('ix_forecast_run_lookup', ['municipality_ibge', 'fetched_at'], unique=False)

    op.create_table('forecast_daily',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('t_min', sa.Float(), nullable=True),
    sa.Column('t_max', sa.Float(), nullable=True),
    sa.Column('precip_mm', sa.Float(), nullable=True),
    sa.Column('precip_prob', sa.SmallInteger(), nullable=True),
    sa.Column('wind_max_kmh', sa.Float(), nullable=True),
    sa.Column('et0_mm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['forecast_run.id'], name=op.f('fk_forecast_daily_run_id_forecast_run')),
    sa.PrimaryKeyConstraint('run_id', 'date', name=op.f('pk_forecast_daily'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecast_daily')
    with op.batch_alter_table('forecast_run', schema=None) as batch_op:
        batch_op.drop_index('ix_forecast_run_lookup')

    op.drop_table('forecast_run')
    # ### end Alembic commands ###
