"""contas: user, farm, planting

Revision ID: 6de6bd3dea9d
Revises: b8ee15d3c6ee
Create Date: 2026-10-02 18:16:14.922845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de6bd3dea9d'
down_revision = 'b8ee15d3c6ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('language_level', sa.String(length=10), nullable=False),
    sa.Column('theme', sa.String(length=10), nullable=False),
    sa.Column('font_size', sa.String(length=15), nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("font_size IN ('normal','grande','muito-grande')", name=op.f('ck_user_font_size')),
    sa.CheckConstraint("language_level IN ('simple','standard','technical')", name=op.f('ck_user_language_level')),
    sa.CheckConstraint("theme IN ('light','dark')", name=op.f('ck_user_theme')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('farm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('municipality_ibge', sa.Integer(), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('soil_group', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['municipality_ibge'], ['municipality.ibge_code'], name=op.f('fk_farm_municipality_ibge_municipality')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_farm_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farm'))
    )
    with op.batch_alter_table('farm', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farm_user_id'), ['user_id'], unique=False)

    op.create_table('planting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("stage IN ('planning','planted','growing','harvested')", name=op.f('ck_planting_stage')),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], name=op.f('fk_planting_crop_id_crop')),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], name=op.f('fk_planting_farm_id_farm'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planting')),
    sa.UniqueConstraint('farm_id', 'crop_id', name='uq_planting_farm_crop')
    )
    with op.batch_alter_table('planting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planting_farm_id'), ['farm_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planting_farm_id'))

    op.drop_table('planting')
    with op.batch_alter_table('farm', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farm_user_id'))

    op.drop_table('farm')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
