"""planejamento: farm_task

Revision ID: 75d3d5527a3e
Revises: 6de6bd3dea9d
Create Date: 2026-10-02 19:13:58.249762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d3d5527a3e'
down_revision = '6de6bd3dea9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], name=op.f('fk_farm_task_crop_id_crop')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_farm_task_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farm_task'))
    )
    with op.batch_alter_table('farm_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farm_task_on_date'), ['on_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_farm_task_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farm_task_user_id'))
        batch_op.drop_index(batch_op.f('ix_farm_task_on_date'))

    op.drop_table('farm_task')
    # ### end Alembic commands ###
