"""mvp essencial: provenance, territory, catalog, zarc

Revision ID: aa70cbea6765
Revises: 
Create Date: 2026-10-02 15:26:55.313896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa70cbea6765'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('official_name', sa.String(length=120), nullable=False),
    sa.Column('scientific_name', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('mvp_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crop')),
    sa.UniqueConstraint('slug', name=op.f('uq_crop_slug'))
    )
    op.create_table('data_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('homepage_url', sa.String(length=500), nullable=True),
    sa.Column('license', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_source')),
    sa.UniqueConstraint('code', name=op.f('uq_data_source_code'))
    )
    op.create_table('soil_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zarc_code', sa.Integer(), nullable=False),
    sa.Column('group_code', sa.Integer(), nullable=False),
    sa.Column('name_simple', sa.String(length=80), nullable=False),
    sa.Column('name_technical', sa.String(length=80), nullable=False),
    sa.Column('description_simple', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_soil_type')),
    sa.UniqueConstraint('zarc_code', name=op.f('uq_soil_type_zarc_code'))
    )
    op.create_table('state',
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('ibge_code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('macro_region', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('uf', name=op.f('pk_state')),
    sa.UniqueConstraint('ibge_code', name=op.f('uq_state_ibge_code'))
    )
    op.create_table('crop_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=120), nullable=False),
    sa.Column('alias_normalized', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('region_scope_uf', sa.String(length=2), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('official','common','regional','scientific','abbreviation','misspelling','zarc')", name=op.f('ck_crop_alias_kind')),
    sa.CheckConstraint("origin IN ('seed','import','ai_suggestion','admin')", name=op.f('ck_crop_alias_origin')),
    sa.CheckConstraint("status IN ('approved','suggested','rejected')", name=op.f('ck_crop_alias_status')),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], name=op.f('fk_crop_alias_crop_id_crop')),
    sa.ForeignKeyConstraint(['source_id'], ['data_source.id'], name=op.f('fk_crop_alias_source_id_data_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crop_alias')),
    sa.UniqueConstraint('crop_id', 'alias_normalized', 'region_scope_uf', name='uq_crop_alias')
    )
    with op.batch_alter_table('crop_alias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crop_alias_alias_normalized'), ['alias_normalized'], unique=False)

    op.create_table('crop_variety',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('name_normalized', sa.String(length=160), nullable=False),
    sa.Column('holder', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], name=op.f('fk_crop_variety_crop_id_crop')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crop_variety')),
    sa.UniqueConstraint('crop_id', 'name_normalized', name='uq_crop_variety')
    )
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('methodology_url', sa.String(length=500), nullable=True),
    sa.Column('refresh_policy', sa.String(length=120), nullable=True),
    sa.Column('usage_status', sa.String(length=20), nullable=False),
    sa.Column('sensitivity', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("sensitivity IN ('none','personal_data_risk')", name=op.f('ck_dataset_sensitivity')),
    sa.CheckConstraint("usage_status IN ('active','reserve','blocked')", name=op.f('ck_dataset_usage_status')),
    sa.ForeignKeyConstraint(['source_id'], ['data_source.id'], name=op.f('fk_dataset_source_id_data_source')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset')),
    sa.UniqueConstraint('code', name=op.f('uq_dataset_code'))
    )
    op.create_table('municipality',
    sa.Column('ibge_code', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_normalized', sa.String(length=120), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('centroid_lat', sa.Float(), nullable=False),
    sa.Column('centroid_lon', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['uf'], ['state.uf'], name=op.f('fk_municipality_uf_state')),
    sa.PrimaryKeyConstraint('ibge_code', name=op.f('pk_municipality'))
    )
    with op.batch_alter_table('municipality', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_municipality_name_normalized'), ['name_normalized'], unique=False)
        batch_op.create_index('ix_municipality_uf_name', ['uf', 'name_normalized'], unique=False)

    op.create_table('dataset_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=120), nullable=False),
    sa.Column('extracted_at', sa.Date(), nullable=False),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('importing','active','superseded','failed')", name=op.f('ck_dataset_version_status')),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], name=op.f('fk_dataset_version_dataset_id_dataset')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_version')),
    sa.UniqueConstraint('dataset_id', 'file_sha256', name='uq_dataset_version_sha')
    )
    with op.batch_alter_table('dataset_version', schema=None) as batch_op:
        batch_op.create_index('uq_dataset_version_current', ['dataset_id'], unique=True, sqlite_where=sa.text('is_current = 1'), postgresql_where=sa.text('is_current'))

    op.create_table('variety_zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('variety_id', sa.Integer(), nullable=False),
    sa.Column('zarc_crop_name', sa.String(length=160), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('municipality_ibge', sa.Integer(), nullable=True),
    sa.Column('soil_type_id', sa.Integer(), nullable=True),
    sa.Column('group_code', sa.String(length=20), nullable=True),
    sa.Column('season_label', sa.String(length=20), nullable=True),
    sa.Column('adaptation_region', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_version.id'], name=op.f('fk_variety_zone_dataset_version_id_dataset_version')),
    sa.ForeignKeyConstraint(['municipality_ibge'], ['municipality.ibge_code'], name=op.f('fk_variety_zone_municipality_ibge_municipality')),
    sa.ForeignKeyConstraint(['soil_type_id'], ['soil_type.id'], name=op.f('fk_variety_zone_soil_type_id_soil_type')),
    sa.ForeignKeyConstraint(['uf'], ['state.uf'], name=op.f('fk_variety_zone_uf_state')),
    sa.ForeignKeyConstraint(['variety_id'], ['crop_variety.id'], name=op.f('fk_variety_zone_variety_id_crop_variety')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variety_zone')),
    sa.UniqueConstraint('dataset_version_id', 'variety_id', 'uf', 'group_code', 'zarc_crop_name', name='uq_variety_zone')
    )
    with op.batch_alter_table('variety_zone', schema=None) as batch_op:
        batch_op.create_index('ix_variety_zone_lookup', ['dataset_version_id', 'uf'], unique=False)

    op.create_table('zarc_zone',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('zarc_crop_name', sa.String(length=160), nullable=False),
    sa.Column('municipality_ibge', sa.Integer(), nullable=False),
    sa.Column('soil_type_id', sa.Integer(), nullable=False),
    sa.Column('cycle_code', sa.SmallInteger(), nullable=False),
    sa.Column('management_code', sa.SmallInteger(), nullable=False),
    sa.Column('climate_code', sa.SmallInteger(), nullable=False),
    sa.Column('management_level', sa.SmallInteger(), nullable=False),
    sa.Column('portaria', sa.String(length=80), nullable=True),
    sa.Column('season_label', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], name=op.f('fk_zarc_zone_crop_id_crop')),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_version.id'], name=op.f('fk_zarc_zone_dataset_version_id_dataset_version')),
    sa.ForeignKeyConstraint(['municipality_ibge'], ['municipality.ibge_code'], name=op.f('fk_zarc_zone_municipality_ibge_municipality')),
    sa.ForeignKeyConstraint(['soil_type_id'], ['soil_type.id'], name=op.f('fk_zarc_zone_soil_type_id_soil_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zarc_zone'))
    )
    with op.batch_alter_table('zarc_zone', schema=None) as batch_op:
        batch_op.create_index('ix_zarc_zone_lookup', ['municipality_ibge', 'crop_id', 'dataset_version_id'], unique=False)

    op.create_table('zarc_window',
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('decendio', sa.SmallInteger(), nullable=False),
    sa.Column('risk_pct', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('decendio BETWEEN 1 AND 36', name=op.f('ck_zarc_window_decendio')),
    sa.CheckConstraint('risk_pct IN (20, 30, 40)', name=op.f('ck_zarc_window_risk_pct')),
    sa.ForeignKeyConstraint(['zone_id'], ['zarc_zone.id'], name=op.f('fk_zarc_window_zone_id_zarc_zone')),
    sa.PrimaryKeyConstraint('zone_id', 'decendio', name=op.f('pk_zarc_window')),
    sqlite_with_rowid=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zarc_window')
    with op.batch_alter_table('zarc_zone', schema=None) as batch_op:
        batch_op.drop_index('ix_zarc_zone_lookup')

    op.drop_table('zarc_zone')
    with op.batch_alter_table('variety_zone', schema=None) as batch_op:
        batch_op.drop_index('ix_variety_zone_lookup')

    op.drop_table('variety_zone')
    with op.batch_alter_table('dataset_version', schema=None) as batch_op:
        batch_op.drop_index('uq_dataset_version_current', sqlite_where=sa.text('is_current = 1'), postgresql_where=sa.text('is_current'))

    op.drop_table('dataset_version')
    with op.batch_alter_table('municipality', schema=None) as batch_op:
        batch_op.drop_index('ix_municipality_uf_name')
        batch_op.drop_index(batch_op.f('ix_municipality_name_normalized'))

    op.drop_table('municipality')
    op.drop_table('dataset')
    op.drop_table('crop_variety')
    with op.batch_alter_table('crop_alias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crop_alias_alias_normalized'))

    op.drop_table('crop_alias')
    op.drop_table('state')
    op.drop_table('soil_type')
    op.drop_table('data_source')
    op.drop_table('crop')
    # ### end Alembic commands ###
