"""seguro rural: insurance_stat (agregado)

Revision ID: b8ee15d3c6ee
Revises: 430aaeab1b2e
Create Date: 2026-10-02 16:34:12.532226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8ee15d3c6ee'
down_revision = '430aaeab1b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('municipality_ibge', sa.Integer(), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('policies_count', sa.Integer(), nullable=False),
    sa.Column('insured_area_ha', sa.Float(), nullable=False),
    sa.Column('insured_amount', sa.Float(), nullable=False),
    sa.Column('premium_total', sa.Float(), nullable=False),
    sa.Column('subsidy_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], name=op.f('fk_insurance_stat_crop_id_crop')),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_version.id'], name=op.f('fk_insurance_stat_dataset_version_id_dataset_version')),
    sa.ForeignKeyConstraint(['municipality_ibge'], ['municipality.ibge_code'], name=op.f('fk_insurance_stat_municipality_ibge_municipality')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insurance_stat')),
    sa.UniqueConstraint('dataset_version_id', 'municipality_ibge', 'crop_id', 'year', name='uq_insurance_stat')
    )
    with op.batch_alter_table('insurance_stat', schema=None) as batch_op:
        batch_op.create_index('ix_insurance_stat_lookup', ['municipality_ibge', 'crop_id', 'year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('insurance_stat', schema=None) as batch_op:
        batch_op.drop_index('ix_insurance_stat_lookup')

    op.drop_table('insurance_stat')
    # ### end Alembic commands ###
